version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: match_odds_db
    environment:
      POSTGRES_DB: match_odds_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: match_odds_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/match_odds_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234